### ISSUE TITLE
Error: lexical error: invalid char in json text

### ISSUE THREAD

**Issue by RJEGR** [ropensci/worrms#10]
Hi everyone,
trying to run any of the code present in the readme or this [link](https://cran.rstudio.com/web/packages/worrms/vignettes/worrms_vignette.html) I've error in 

**Error: lexical error: invalid char in json text.
                                       <html><head><meta http-equiv='C
                     (right here) ------^**

I've thinking this error is with json version but not sure I do not how to fix it to connect to worms API. Any suggestion ?

> sessionInfo()
R version 3.4.2 (2017-09-28)Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.10
Matrix products: defaultBLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
locale: [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=es_MX.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=es_MX.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=es_MX.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=es_MX.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] jsonlite_1.5       worrms_0.2.6.9100  bindrcpp_0.2       dplyr_0.7.4
[5] DT_0.4             shiny_1.0.5        ggplot2_2.2.1.9000 phyloseq_1.22.3

**Comment by sckott** [comment]
thanks for your report @RJEGR  - everything is working fine for me locally, let's sort it out.

What output does running this give you:

```r
 wm_record(id = 105706, verbose = TRUE)
```

**Comment by RJEGR** [comment]
Hi sckott,

I've tried it but unfortunately the error persist. :( OK. thinking in brief, it suppose than `wm_record` try to access a json format within marinespecies webpage but the error I've is because my code is trying to connect with a html version instead of the json. because the error printed is because in the begining of the css code the `wm_record` identify a non-json text (because it is css). Similar error as [here] (https://github.com/jeroen/jsonlite/issues/147). does it make sence for anyone?

```r
*   Trying 193.191.134.34...
* TCP_NODELAY set
* Connected to www.marinespecies.org (193.191.134.34) port 80 (#0)
> GET /rest/AphiaRecordByAphiaID/105706 HTTP/1.1
Host: www.marinespecies.org
User-Agent: libcurl/7.55.1 r-curl/3.2 crul/0.5.2
Accept-Encoding: gzip, deflate
Accept: application/json, text/xml, application/xml, */*

< HTTP/1.1 200 OK
< Date: Tue, 17 Apr 2018 20:53:54 GMT
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: text/html; charset="UTF-8"
< Content-Length: 65453
< Accept-Ranges: none
< Via: HTTP/1.1 sophos.http.proxy:3128
< Connection: close
<
** Closing connection 0
Error: lexical error: invalid char in json text.
                                       <html><head><meta http-equiv='C
                     (right here) ------^**
```


Also when I tried the rest of the methods in the worrms readme post the error persist.

**Comment by RJEGR** [comment]
Dear Scott,

the problem was fixed when change my internet connection. for some reason the proxy was masking the worms API .

thanks!!!!

**Comment by sckott** [comment]
I was in the middle of writing:

> you are behind a proxy, see the response header line `< Via: HTTP/1.1 sophos.http.proxy:3128`. You probably need to pass in your proxy details.

but the other option is to not be behind the proxy, i'll try to make a fix though as others will surely have the same problem
