### ISSUE TITLE
Error when using wm_records_taxamatch( )

### ISSUE THREAD

**Issue by GuilleFB** [ropensci/worrms#25]
When using the wm_records_taxamatch ( ) command to match species, if the species is a variety it returns an error.
For instance:
Using wm_records_taxamatch ("Cystoseira humilis myriophylloides") generates an error: Error: (204) No Content - AphiaRecordsByMatchNames
However, if used by entering wm_records_taxamatch ("Cystoseira humilis var. Myriophylloides") it finds a match.
Isn't there any way that it doesn't take into account the variety of the species?

**Comment by bart-v** [comment]
The fuzzy match does not work well on non-binomials, indeed.
So adding the infraspecific marked will improve the results
This is not something we can fix in the short run
