### ISSUE TITLE
Fuzzy matching not working with wm_records_names function

### ISSUE THREAD

**Issue by johnny3125** [ropensci/worrms#26]

**Comment by bart-v** [comment]
This is normal, as the call uses the function
`AphiaRecordsByNames()`
https://github.com/ropensci/worrms/blob/a07d17554063f0a3a9ef9a132a6ecd8b6cdfc9b8/R/wm_records_names.R#L26

Fuzzy match is only available via 
`AphiaRecordsByMatchNames`

This is an API change that has been communicated a long time ago...
`2013-07-17 added function matchAphiaRecordsByNames (...) This results in removing/ignoring the fuzzy parameter in all other functions`

**Comment by pieterprovoost** [comment]
But the `fuzzy` parameter is still there. Will provide a fix in https://github.com/ropensci/worrms/pull/41.
