### ISSUE TITLE
Add retrying?

### ISSUE THREAD

**Issue by maelle** [ropensci/worrms#28]
I just got this error 

```r
 Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) :
  Error in the HTTP2 framing layer
```

for a query that has worked previously and worked again after that. Would using RETRY instead of GET help with this?

**Comment by bart-v** [comment]
Feel free to make a PR

**Comment by bart-v** [comment]
Duplicate of https://github.com/ropensci/worrms/issues/27
Closing
