### ISSUE TITLE
Typo in help wm_records_names and wm_records_taxamatch

### ISSUE THREAD

**Issue by vijaybarve** [ropensci/worrms#33]
wm_records_names	Get records for **onen** or more taxonomic name(s)
wm_records_taxamatch	Get records for **onen** or more taxonomic name(s) using the TAXAMATCH fuzzy matching algorithm

<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by pieterprovoost** [comment]
Fix in https://github.com/ropensci/worrms/pull/41.
