### ISSUE TITLE
Maintenance status / help needed?

### ISSUE THREAD

**Issue by maelle** [ropensci/worrms#34]
:wave: @bart-v 

Do you still intend to become this package's maintainer?

If so do you need any help? For instance an aspect where you'd appreciate some tips, contributions, a PR review? Do you need an invitation to our friendly Slack workspace?

**Comment by bart-v** [comment]
Yes, we do.
I don't have time do do much myself, but I will redistribute the work to others in VLIZ

For the help, I think we are OK now

**Comment by maelle** [comment]
:tada: Thanks! See also #35
