### ISSUE TITLE
Add new maintainer to DESCRIPTION

### ISSUE THREAD

**Issue by maelle** [ropensci/worrms#35]
@bart-v thanks for your answer! Could you please add yourself to the DESCRIPTION file with the "aut" and "cre" roles so that the maintainer change is registered? Thank you!!

**Comment by bart-v** [comment]
OK, done

**Comment by maelle** [comment]
Thank you!

**Comment by jeroen** [comment]
You can have only 1 cre: https://github.com/r-universe/ropensci/runs/8268677773?check_suite_focus=true

**Comment by maelle** [comment]
yes see #36

**Comment by bart-v** [comment]
Sigh...

**Comment by maelle** [comment]
Sorry for the clunkiness @bart-v and thanks again to you & your team for maintaining this package! :ocean:
