### ISSUE TITLE
wm_records_taxamatch should not throw an error on empty results

### ISSUE THREAD

**Issue by pieterprovoost** [ropensci/worrms#38]
`wm_records_taxamatch()` throws an error when none of the submitted names have results. If only some names do not have results, the empty results sets are represented by an empty tibble. This inconsistency complicates integration, but moreover, common practice is to only throw errors for unexpected conditions which prevent the function from continuing.

```r
> worrms::wm_records_taxamatch("xxxxxxxx")
Error: (204) No Content - AphiaRecordsByMatchNames
> worrms::wm_records_taxamatch(c("xxxxxxxx", "Abra alba"))
[[1]]
# A tibble: 0 × 0

[[2]]
# A tibble: 1 × 27
  AphiaID url       scien…¹ autho…² status unacc…³ taxon…⁴ rank  valid…⁵ valid…⁶ valid…⁷ paren…⁸ kingdom phylum class order
    <int> <chr>     <chr>   <chr>   <chr>  <lgl>     <int> <chr>   <int> <chr>   <chr>     <int> <chr>   <chr>  <chr> <chr>
1  141433 https://… Abra a… (W. Wo… accep… NA          220 Spec…  141433 Abra a… (W. Wo…  138474 Animal… Mollu… Biva… Card…
# … with 11 more variables: family <chr>, genus <chr>, citation <chr>, lsid <chr>, isMarine <int>, isBrackish <lgl>,
#   isFreshwater <lgl>, isTerrestrial <lgl>, isExtinct <lgl>, match_type <chr>, modified <chr>, and abbreviated variable
#   names ¹​scientificname, ²​authority, ³​unacceptreason, ⁴​taxonRankID, ⁵​valid_AphiaID, ⁶​valid_name, ⁷​valid_authority,
#   ⁸​parentNameUsageID
```

**Comment by bart-v** [comment]
204 is not an error, it's best practice
But debated :)
https://apihandyman.io/empty-lists-http-status-code-200-vs-204-vs-404/#the-not-so-current-204
If R does not like this, it can easily be fixed, I assume

**Comment by pieterprovoost** [comment]
Fixed using `on_error = warning`, although this results in a tibble instead of a list. I will submit a PR to fix that issue.
