### ISSUE TITLE
In the current "worrms" version, what is the function equivalent to the old version's "wormsbynames" function?

### ISSUE THREAD

**Issue by tadeu95** [ropensci/worrms#43]
Sorry if this has been asked before, but in the old package (worms) there was this function "wormsbynames". It takes character vector with taxon names and retrives AphiaRecords from WoRMS. For each name given as input, only the one AphiaRecord is retrived. 
Is there a new function in the new version (worrms) that is equivalent to that?
Thank you!
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by bart-v** [comment]
Yes, `wm_records_taxamatch()`
