### ISSUE TITLE
fuzzy matching not available for wm_records_names

### ISSUE THREAD

**Issue by yuliaUU** [ropensci/worrms#47]
I am having issues extracting the data:
for instance

```r
get_wm_records("Conus caillaudi")
#Error fetching records: Error: (204) No Content - AphiaRecordsByNames

```
While in WoRMS I see that record exist: https://www.marinespecies.org/aphia.php?p=taxdetails&id=426438
```r
get_wm_records("Conus caillaudii")
#[[1]]
# A tibble: 1 × 27
```
the only difference is species name missing the second `i` at the end. I thought this function is still going to return the correct name. or does it not do any fuzzy matching? if no, can you suggest a workaround?

**Comment by yuliaUU** [comment]
it looks like fuzzy matching not available for `wm_records_names`
```r
worrms::wm_records_names("Conus caillaudi",fuzzy = TRUE) 
Error: (204) No Content - AphiaRecordsByNames 
worrms::wm_records_name("Conus caillaudi",fuzzy = TRUE) 
# A tibble: 1 × 27  
```

**Comment by bart-v** [comment]
Correct and duplicated issue, see https://github.com/ropensci/worrms/issues/26
