### ISSUE TITLE
marine_only=TRUE does not work in wm_records_name

### ISSUE THREAD

**Issue by yuliaUU** [ropensci/worrms#48]
I was checking the freshwater species "Enneacampus ansorgii", so i would expect if i set marine_only argument to TRUE: I wont an empty dataframe
```r
worrms::wm_records_name("Enneacampus ansorgii",marine_only=TRUE)
```
but the function works. 
AM i interpreting the marine_only argument wrong?

**Comment by bart-v** [comment]
_Enneacampus ansorgii_ is marked as brackish and fresh in WoRMS: https://www.marinespecies.org/aphia.php?p=taxdetails&id=280675
`marine_only` includes marine or brackish
So this is normal behavior
